version: '3'
services:
  app:
    image: taiphamdac/3d_stedy:7d078432a49eec78ee85254203b9de2a81db7c4a
    ports:
      - '3000:3000'
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
