query leads($filter: FilterLeadInput){
    leads(filter: $filter){
        items{
            address
            community{
                createdAt
                deletedAt
                description
                id
                name
                state
                status
                thumbnail_url
                updatedAt
            }
            communityId
            consultant
            createdAt
            deletedAt
            email
            full_name
            home_specialist
            id
            lead_source
            phone
            product{
                SKU
                availableSizes
                brandName
                code
                communitiesId
                createdAt
                defaultSize
                deletedAt
                description
                enable
                id
                moduleType
                name
                note
                offset
                path
                position
                price
                serieIds
                storeIds
                thumbnail
                updatedAt
            }
            productId
            sale_agent
            state
            status
            tenantId
            total_price
            updatedAt
        }
        total
    }
}