query me {
  me {
    accessToken
    createdAt
    email
    fullName
    id
    password
    refreshToken
    roles {
      capabilities
      createdAt
      id
      roleName
      updatedAt
    }
    updatedAt
    username
  }
}
