name: CI/CD Pipeline

on:
  push:
    branches: [ build-docker ]
  pull_request:
    branches: [ build-docker ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: taiphamdac/3d_stedy
  SERVER_HOST: 64.23.206.54
  SERVER_USERNAME: root
  SERVER_PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/build-docker'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: taiphamdac
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USERNAME }}
          password: ${{ env.SERVER_PASSWORD }}
          script: |
            # Create directory if it doesn't exist
            mkdir -p /var/www/3d_stedy
            
            # Pull latest image
            docker pull ${{ env.IMAGE_NAME }}:${{ github.sha }}
            
            # Backup current deployment
            if [ -d "/var/www/3d_stedy" ]; then
              tar -czf /var/www/3d_stedy_backup_$(date +%Y%m%d_%H%M%S).tar.gz /var/www/3d_stedy
            fi
            
            # Update deployment
            cd /var/www/3d_stedy
            
            # Create docker-compose.yml if it doesn't exist
            cat > docker-compose.yml << EOL
            version: '3'
            services:
              app:
                image: ${{ env.IMAGE_NAME }}:${{ github.sha }}
                ports:
                  - "3000:80"
                restart: always
                healthcheck:
                  test: ["CMD", "curl", "-f", "http://localhost:80/health"]
                  interval: 30s
                  timeout: 10s
                  retries: 3
                  start_period: 40s
            EOL
            
            docker-compose down
            docker system prune -f
            docker-compose up -d
            
            # Wait for container to start
            echo "Waiting for container to start..."
            sleep 30
            
            # Check container status
            if ! docker ps | grep -q "3d_stedy-app-1"; then
              echo "Container failed to start"
              docker-compose logs
              exit 1
            fi
            
            # Health check
            echo "Checking container health..."
            for i in {1..10}; do
              if curl -f http://localhost:3000/health; then
                echo "Health check passed!"
                break
              fi
              if [ $i -eq 10 ]; then
                echo "Health check failed"
                docker-compose logs
                exit 1
              fi
              echo "Waiting for service to be ready... ($i/10)"
              sleep 3
            done 