name: CI/CD Pipeline

on:
  push:
    branches: [ build-docker, main ]
  pull_request:
    branches: [ build-docker, main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: taiphamdac/3d_stedy
  SERVER_HOST: 64.23.206.54
  SERVER_USERNAME: root
  API_DOMAIN: http://137.184.13.30:3000
  API_URL: /graphql

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run ESLint
        run: npm run lint

  build-test-deploy:
    needs: lint-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/build-docker' || github.ref == 'refs/heads/main')
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Create production environment file
        run: |
          cat > .env.production << "EOL"
          NODE_ENV=production
          VITE_NAME_ENV=production
          VITE_PUBLIC_API_URL="${{ env.API_URL }}"
          VITE_PUBLIC_API_DOMAIN="${{ env.API_DOMAIN }}"
          EOL

      - name: Build application
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: taiphamdac
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script_stop: true
          script: |
            # Pull latest image
            docker pull ${{ env.IMAGE_NAME }}:latest
            
            # Create directory for persistent data
            mkdir -p /root/app/nginx
            
            # Create the nginx configuration file
            cat > /root/app/nginx/nginx.conf << 'EOL'
            server {
                listen 3000;
                server_name _;
                root /app/dist;
                
                # Compression
                gzip on;
                gzip_comp_level 6;
                gzip_vary on;
                gzip_min_length 1000;
                gzip_proxied any;
                gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
                gzip_buffers 16 8k;
                
                # Health check endpoint
                location /health {
                    return 200 'OK';
                    add_header Content-Type text/plain;
                }
                
                # GraphQL API endpoint
                location /graphql {
                    proxy_pass http://137.184.13.30:3000/graphql;
                    proxy_http_version 1.1;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }
                
                # All other requests go to the static build
                location / {
                    try_files $uri $uri/ /index.html;
                    add_header Cache-Control "public, max-age=3600";
                }
                
                # Serve static assets with long cache time
                location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
                    expires 7d;
                    add_header Cache-Control "public, max-age=604800";
                }
            }
            EOL
            
            # Create docker-compose.yml
            cat > /root/app/docker-compose.yml << 'EOL'
            version: '3'
            services:
              app:
                image: taiphamdac/3d_stedy:latest
                container_name: 3d_stedy_app
                restart: always
                environment:
                  NODE_ENV: production
                  VITE_PUBLIC_API_DOMAIN: http://137.184.13.30:3000
                  VITE_PUBLIC_API_URL: /graphql
                ports:
                  - "3000:3000"
                volumes:
                  - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
                networks:
                  - app_network
                healthcheck:
                  test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
                  interval: 30s
                  timeout: 10s
                  retries: 3
                  start_period: 40s
                logging:
                  driver: "json-file"
                  options:
                    max-size: "10m"
                    max-file: "3"
            
            networks:
              app_network:
                driver: bridge
            EOL
            
            # Move to the app directory
            cd /root/app
            
            # Stop and remove existing containers
            docker-compose down || true
            
            # Clean up unused resources
            docker system prune -f --volumes
            
            # Start the new deployment
            docker-compose up -d
            
            # Wait for container to start
            echo "Waiting for container to start..."
            sleep 10
            
            # Check container status
            if ! docker ps | grep -q "3d_stedy_app"; then
              echo "Container failed to start"
              docker-compose logs
              exit 1
            fi
            
            # Health check with proper error handling
            echo "Checking container health..."
            max_attempts=12
            for i in $(seq 1 $max_attempts); do
              if curl -sf http://localhost:3000/health > /dev/null; then
                echo "Health check passed!"
                exit 0
              fi
              echo "Waiting for service to be ready... ($i/$max_attempts)"
              sleep 5
            done
            
            echo "Health check failed after $max_attempts attempts"
            docker-compose logs
            exit 1